export const styles = {
    arrow: {
      position: "absolute",
      left: "10px",
      top: { xs: "46px", lg: "30px" },
    },
    textfeildContainer: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "column",
      marginTop: "-70px",
    },
    title: {
      color: "#18161B",
      fontFamily: '"Montserrat Alternates", sans-serif',
      fontSize: "24px",
      fontWeight: "600",
      marginTop: "40px",
    },
    profileTitle: {
      width: "100%",
      height: "25vh",
      background: "#F5BF45",
      textAlign: "center",
    },
    editContainer: {
      position: "absolute",
      top: "20px",
      right: "0px",
      padding: "10px",
      background: "red",
      borderRadius: "100%",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      color: "#FFF",
    },
    imageContainer: {
      width: "170px",
      height: "170px",
      padding: "3px",
      background: "#FFF",
      position: "relative",
      top: "-80px",
      borderRadius: "100%",
      overFlow: "none",
    },
    image: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      borderRadius: "100%",
      overFlow: "none",
    },
    profileContainer: {
      display: "flex",
      alignItems: "center",
      flexDirection: "column",
    },
    input: {
      display: "none",
      border: "1px solid red",
    },
  };