export const BestSellerStyles = {
    bestSellerContainer: {
      display: "flex",
      justifyContent: "flex-start",
      flexDirection: "column",
      alignItems: "center",
      width: "100%",
      padding: "10px",
      boxSizing: "border-box",
      background: "#fff",
      marginBottom: "20px",
    },
    bestSellerText: {
      fontSize: "20px",
      fontWeight: "bold",
      width: "95%",
      textAlign: "start",
    },
    bestSellerItemText: {
      fontSize: "15px",
      fontWeight: "bold",
      marginTop: "10px",
    },
    bestSellerItemPrice: {
      display: "flex",
      justifyContent: "flex-start",
      alignItems: "center",
    },
    bestSellerItemPriceText: {
      color: "#F62B2A",
      fontSize: "15px",
      fontWeight: "bold",
      marginRight: "15px",
    },
    bestSellerItemPriceText1: {
      color: "  #A9A9A9",
      fontSize: "15px",
      fontWeight: "bold",
    },
    quantityContainer: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      width: { xs: "95%", md: "200px", lg: "300px" },
      marginTop: "10px",
      height: { xs: "40px", md: "50px" },
      borderRadius: "30px",
      backgroundColor: "#F5BF45",
    },
    removeIcon: {
      color: "#fff",
      height: "100%",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      width: { xs: "30%", md: "20%" },
      borderRight: "1px solid #fff",
      cursor: "pointer",
    },
    addIcon: {
      color: "#fff",
      height: "100%",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      width: { xs: "30%", md: "20%" },
      borderLeft: "1px solid #fff",
      cursor: "pointer",
    },
  };