export const styles = {
    li: {
      width: "100%",
      boxSizing: "border-box",
      padding: "10px",
      display: "flex",
      gap: "20px",
      justifyContent: "flex-start",
      alignItems: "center",
      borderBottom: "1px solid grey",
      color: "#A9A9A9",
      fontFamily: '"Montserrat Alternates", sans-serif',
      fontSize: "14px",
      fontWeight: "600",
      ": hover": {
        color: "#E7AC27",
        borderBottom: "1px solid #E7AC27",
        transform: `scale(1.1)`,
        transition: ".5s",
      },
    },
    liSelected:{
      width: "100%",
      boxSizing: "border-box",
      padding: "10px",
      display: "flex",
      gap: "20px",
      justifyContent: "flex-start",
      alignItems: "center",
      color: "#E7AC27",
      borderBottom: "1px solid #E7AC27",
      transform: `scale(1.1)`,
      transition: ".5s",
      fontFamily: '"Montserrat Alternates", sans-serif',
      fontSize: "14px",
      fontWeight: "600",
    },
    text: {
      ": hover": {
        color: "#18161B",
        fontFamily: '"Montserrat Alternates", sans-serif',
        fontSize: "15px",
        fontWeight: "600",
      },
    },
    sidebarNavSection: {
      width: "100%",
      alignItems: "center",
      justifyContent: "space-between",
      background: "#F5BF45",
      flexDirection: "row",
      padding: "10px",
    },
    close: {
      width: "30px",
      height: "30px",
      objectFit: "cover",
    },
    sideBarContainer: {
      width: "100%",
      height: "100vh",
      position: "absolute",
      top: "0px",
      left: "0px",
      zIndex: "999",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      background: "#7F7F7F",
      overflow: "hidden",
      transition: "1s",
    },
    sideBarContainerNone: {
      width: "0%",
      height: "100vh",
      zIndex: "999",
      position: "absolute",
      top: "-10px",
      left: "0px",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
      background: "#7F7F7F",
      overflow: "hidden",
      transition: "1s",
    },
    sideBar: {
      width: "270px",
      height: "100vh",
      background: "#FFF",
      position: "absolute",
      top: "0px",
      left: "0px",
      zIndex: "1000",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: "10px",
      boxSizing: "border-box",
      overflow: "hidden",
      transition: "1s",
    },
    sideBarNone: {
      width: "0px",
      height: "100vh",
      background: "#FFF",
      position: "absolute",
      top: "0px",
      left: "0px",
      zIndex: "1000",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      boxSizing: "border-box",
      overflow: "hidden",
      transition: "1s",
    },
    hamburger: {
      width: "50px",
      height: "50px",
      display: {sm:'none',xs:'flex'},
      alignItems: "center",
      justifyContent: "center",
      padding: "0px",
      background: "#E7AC27",
      borderRadius: "100%",
      overflow: "hidden",
      color: "white",
    },
    container: {
      width: "100%",
      boxSizing: "border-box",
      padding: "10px",
      background: "#F5BF45",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
    },
    profileContainer: {
      width: "50px",
      height: "50px",
      borderRadius: "100%",
      padding: "3px",
      background: "#E7AC27",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    profile: {
      width: "100%",
      height: "100%",
      borderRadius: "100%",
      padding: "10px",
    },
  };